set xrange[0:31]; set yrange[0:31]; set size ratio 1; unset xtics; unset ytics; set pm3d map; set terminal pngcairo
set output '0.png'
splot '0' matrix
set output '1.png'
splot '1' matrix
set output '2.png'
splot '2' matrix
set output '3.png'
splot '3' matrix
set output '4.png'
splot '4' matrix
set output '5.png'
splot '5' matrix
set output '6.png'
splot '6' matrix
set output '7.png'
splot '7' matrix
set output '8.png'
splot '8' matrix
set output '9.png'
splot '9' matrix
set output '10.png'
splot '10' matrix
set output '11.png'
splot '11' matrix
set output '12.png'
splot '12' matrix
set output '13.png'
splot '13' matrix
set output '14.png'
splot '14' matrix
set output '15.png'
splot '15' matrix
set output '16.png'
splot '16' matrix
set output '17.png'
splot '17' matrix
set output '18.png'
splot '18' matrix
set output '19.png'
splot '19' matrix
set output '20.png'
splot '20' matrix
set output '21.png'
splot '21' matrix
set output '22.png'
splot '22' matrix
set output '23.png'
splot '23' matrix
set output '24.png'
splot '24' matrix
set output '25.png'
splot '25' matrix
set output '26.png'
splot '26' matrix
set output '27.png'
splot '27' matrix
set output '28.png'
splot '28' matrix
set output '29.png'
splot '29' matrix
set output '30.png'
splot '30' matrix
set output '31.png'
splot '31' matrix
set output '32.png'
splot '32' matrix
set output '33.png'
splot '33' matrix
set output '34.png'
splot '34' matrix
set output '35.png'
splot '35' matrix
set output '36.png'
splot '36' matrix
set output '37.png'
splot '37' matrix
set output '38.png'
splot '38' matrix
set output '39.png'
splot '39' matrix
set output '40.png'
splot '40' matrix
set output '41.png'
splot '41' matrix
set output '42.png'
splot '42' matrix
set output '43.png'
splot '43' matrix
set output '44.png'
splot '44' matrix
set output '45.png'
splot '45' matrix
set output '46.png'
splot '46' matrix
set output '47.png'
splot '47' matrix
set output '48.png'
splot '48' matrix
